import { Decimal } from 'decimal.js';
import type { WalletPosition, WalletTradeMatch } from '@prisma/client';
import { D, exact, pct, quantile } from '../walletPositions/math.js';
import { QUALITY_WARNINGS as W } from './warnings.js';

export type PositionWithMatches = WalletPosition & { matches: WalletTradeMatch[] };
const vals=(ps:PositionWithMatches[],key:'rawRealizedPnlSol'|'knownAllInRealizedPnlSol'|'rawRealizedRoiPct'|'knownAllInRealizedRoiPct'|'knownCostBasisSol')=>ps.flatMap(p=>p[key]===null?[]:[D(p[key] as string)]);
const mean=(v:Decimal[])=>v.length?v.reduce((a,b)=>a.plus(b),D(0)).div(v.length):null;
const rate=(n:number,d:number)=>d?pct(D(n),D(d)):null;
export function sampleTier(n:number){return n<5?'VERY_SMALL':n<20?'SMALL':n<50?'MODERATE':n<200?'LARGE':'VERY_LARGE';}
export function isEligible(p:PositionWithMatches){const warnings=JSON.parse(p.warningCodes) as string[];return p.status==='CLOSED'&&p.rawRealizedPnlSol!==null&&p.rawRealizedRoiPct!==null&&!warnings.some(w=>w.startsWith('TRANSFER_')||w==='UNMATCHED_SELL'||w==='OVERSELL')&&D(p.unknownBasisAmount??0).isZero()&&D(p.unmatchedSellAmount??0).isZero();}
export function sizeBucket(v:string|null){if(!v)return'unknown';const x=D(v);return x.lt(.05)?'under 0.05 SOL':x.lt(.1)?'0.05–0.10 SOL':x.lt(.25)?'0.10–0.25 SOL':x.lt(.5)?'0.25–0.50 SOL':x.lt(1)?'0.50–1.00 SOL':'over 1.00 SOL';}
export function holdingBucket(s:number|null){return s===null?'open/unknown':s<300?'under 5m':s<1800?'5–30m':s<3600?'30–60m':s<14400?'1–4h':s<86400?'4–24h':'over 24h';}
export function summarize(positions:PositionWithMatches[],completeHistory:boolean){
 const eligible=positions.filter(isEligible),excluded=positions.filter(p=>!isEligible(p));const raw=vals(eligible,'rawRealizedPnlSol'),all=vals(eligible,'knownAllInRealizedPnlSol'),rawRoi=vals(eligible,'rawRealizedRoiPct'),allRoi=vals(eligible,'knownAllInRealizedRoiPct'),sizes=vals(eligible,'knownCostBasisSol');const holding=eligible.flatMap(p=>p.holdingDurationSeconds===null?[]:[D(p.holdingDurationSeconds)]);const gains=raw.filter(x=>x.gt(0)),losses=raw.filter(x=>x.lt(0));const grossGain=gains.reduce((a,b)=>a.plus(b),D(0));const grossLoss=losses.reduce((a,b)=>a.plus(b.abs()),D(0));const positive=raw.filter(x=>x.gt(0)).length,negative=raw.filter(x=>x.lt(0)).length,flat=raw.filter(x=>x.isZero()).length;const largestGain=gains.length?Decimal.max(...gains):null,largestLoss=losses.length?Decimal.max(...losses.map(x=>x.abs())):null;const med=quantile(raw,.5),avg=mean(raw);const warnings=new Set<string>();const tier=sampleTier(eligible.length);if(tier==='VERY_SMALL')warnings.add(W.VERY_SMALL_SAMPLE);else if(tier==='SMALL')warnings.add(W.SMALL_SAMPLE);if(!completeHistory)warnings.add(W.INCOMPLETE_WALLET_HISTORY);if(positions.length&&eligible.length/positions.length<.5)warnings.add(W.LOW_ELIGIBLE_COVERAGE);if(positions.some(p=>D(p.transferInAmount??0).gt(0)||D(p.transferOutAmount??0).gt(0)))warnings.add(W.TRANSFER_AFFECTED_SAMPLE);if(positions.some(p=>D(p.unmatchedSellAmount??0).gt(0)))warnings.add(W.UNMATCHED_SELLS_PRESENT);if(eligible.some(p=>p.knownAllInRealizedPnlSol===null))warnings.add(W.MISSING_FEE_DATA);const gainContribution=largestGain&&grossGain.gt(0)?largestGain.div(grossGain).mul(100):null;if(gainContribution?.gt(50))warnings.add(W.OUTLIER_DOMINATED);
 const hb={under5m:holding.filter(x=>x.lt(300)).length,under30m:holding.filter(x=>x.lt(1800)).length,under1h:holding.filter(x=>x.lt(3600)).length,oneTo4h:holding.filter(x=>x.gte(3600)&&x.lt(14400)).length,fourTo24h:holding.filter(x=>x.gte(14400)&&x.lt(86400)).length,over24h:holding.filter(x=>x.gte(86400)).length};
 return{eligible,excluded,tier,warnings,positive,negative,flat,positiveAll:all.filter(x=>x.gt(0)).length,negativeAll:all.filter(x=>x.lt(0)).length,rawPositiveRate:rate(positive,raw.length),allPositiveRate:rate(all.filter(x=>x.gt(0)).length,all.length),medianRaw:med,meanRaw:avg,p25Raw:quantile(raw,.25),p75Raw:quantile(raw,.75),minRaw:raw.length?Decimal.min(...raw):null,maxRaw:raw.length?Decimal.max(...raw):null,medianAll:quantile(all,.5),meanAll:mean(all),medianRawRoi:quantile(rawRoi,.5),meanRawRoi:mean(rawRoi),p25RawRoi:quantile(rawRoi,.25),p75RawRoi:quantile(rawRoi,.75),medianAllRoi:quantile(allRoi,.5),meanAllRoi:mean(allRoi),grossGain,grossLoss,profitFactor:grossLoss.isZero()?null:grossGain.div(grossLoss),gainContribution,lossContribution:largestLoss&&grossLoss.gt(0)?largestLoss.div(grossLoss).mul(100):null,medianHolding:quantile(holding,.5),meanHolding:mean(holding),p25Holding:quantile(holding,.25),p75Holding:quantile(holding,.75),medianSize:quantile(sizes,.5),meanSize:mean(sizes),p25Size:quantile(sizes,.25),p75Size:quantile(sizes,.75),distinctTokens:new Set(eligible.map(p=>p.tokenId)).size,transferCount:positions.filter(p=>D(p.transferInAmount??0).gt(0)||D(p.transferOutAmount??0).gt(0)).length,unmatchedCount:positions.filter(p=>D(p.unmatchedSellAmount??0).gt(0)).length,holdingBuckets:hb,medianMeanDivergence:med&&avg?avg.minus(med):null,repeatedTokenConcentration:eligible.length?D(eligible.length-new Set(eligible.map(p=>p.tokenId)).size).div(eligible.length).mul(100):null};
}
export function summaryFields(s:ReturnType<typeof summarize>){return{sampleSizeTier:s.tier,totalPositionCount:s.eligible.length+s.excluded.length,eligibleClosedCount:s.eligible.length,eligibleOpenCount:s.excluded.filter(p=>p.status==='OPEN').length,excludedCount:s.excluded.length,highConfidenceCount:s.eligible.filter(p=>p.confidence==='HIGH').length,lowerConfidenceCount:s.eligible.filter(p=>p.confidence!=='HIGH').length,positiveRawCount:s.positive,negativeRawCount:s.negative,flatRawCount:s.flat,positiveAllInCount:s.positiveAll,negativeAllInCount:s.negativeAll,rawPositiveRatePct:s.rawPositiveRate,allInPositiveRatePct:s.allPositiveRate,medianRawPnlSol:exact(s.medianRaw),meanRawPnlSol:exact(s.meanRaw),p25RawPnlSol:exact(s.p25Raw),p75RawPnlSol:exact(s.p75Raw),minRawPnlSol:exact(s.minRaw),maxRawPnlSol:exact(s.maxRaw),medianAllInPnlSol:exact(s.medianAll),meanAllInPnlSol:exact(s.meanAll),medianRawRoiPct:exact(s.medianRawRoi),meanRawRoiPct:exact(s.meanRawRoi),p25RawRoiPct:exact(s.p25RawRoi),p75RawRoiPct:exact(s.p75RawRoi),medianAllInRoiPct:exact(s.medianAllRoi),meanAllInRoiPct:exact(s.meanAllRoi),grossGainSol:exact(s.grossGain),grossLossSol:exact(s.grossLoss),profitFactor:exact(s.profitFactor),largestGainContributionPct:exact(s.gainContribution),largestLossContributionPct:exact(s.lossContribution),medianHoldingSeconds:exact(s.medianHolding),meanHoldingSeconds:exact(s.meanHolding),p25HoldingSeconds:exact(s.p25Holding),p75HoldingSeconds:exact(s.p75Holding),medianPositionSizeSol:exact(s.medianSize),meanPositionSizeSol:exact(s.meanSize),p25PositionSizeSol:exact(s.p25Size),p75PositionSizeSol:exact(s.p75Size),observedDistinctTokenCount:s.distinctTokens,transferAffectedCount:s.transferCount,unmatchedSellCount:s.unmatchedCount,eligibleCoveragePct:rate(s.eligible.length,s.eligible.length+s.excluded.length),consistencyJson:JSON.stringify({medianMeanDivergence:exact(s.medianMeanDivergence),repeatedTokenConcentrationPct:exact(s.repeatedTokenConcentration)}),holdingBucketsJson:JSON.stringify(s.holdingBuckets),warningCodes:JSON.stringify([...s.warnings].sort())};}
