export const QUALITY_WARNINGS = {
  VERY_SMALL_SAMPLE:'VERY_SMALL_SAMPLE', SMALL_SAMPLE:'SMALL_SAMPLE',
  INCOMPLETE_WALLET_HISTORY:'INCOMPLETE_WALLET_HISTORY', LOW_ELIGIBLE_COVERAGE:'LOW_ELIGIBLE_COVERAGE',
  TRANSFER_AFFECTED_SAMPLE:'TRANSFER_AFFECTED_SAMPLE', UNMATCHED_SELLS_PRESENT:'UNMATCHED_SELLS_PRESENT',
  MISSING_FEE_DATA:'MISSING_FEE_DATA', OUTLIER_DOMINATED:'OUTLIER_DOMINATED',
  PARTIAL_MARKET_OUTCOMES:'PARTIAL_MARKET_OUTCOMES', STALE_MARKET_CONTEXT:'STALE_MARKET_CONTEXT',
  CATEGORY_SAMPLE_TOO_SMALL:'CATEGORY_SAMPLE_TOO_SMALL', RECENT_WINDOW_TOO_SMALL:'RECENT_WINDOW_TOO_SMALL',
  OLDER_WINDOW_TOO_SMALL:'OLDER_WINDOW_TOO_SMALL', MIXED_EVENT_CONFIDENCE:'MIXED_EVENT_CONFIDENCE',
} as const;
