/* eslint-disable @typescript-eslint/no-explicit-any */
import { beforeEach, describe, expect, it } from 'vitest';
import { buildTestApp, resetDb, type TestApp } from '../helpers.js';
import { syntheticAddress } from '@memecoin-lab/shared';

let ctx:TestApp;
beforeEach(async()=>{ctx=await buildTestApp();await resetDb(ctx.prisma);});
async function setup(backfillComplete=true){const wallet=await ctx.prisma.trackedWallet.create({data:{address:syntheticAddress(7001),source:'activity'}});await ctx.prisma.walletSyncState.create({data:{walletId:wallet.id,backfillComplete}});const token=await ctx.prisma.token.create({data:{mintAddress:syntheticAddress(7002),source:'activity'}});return{wallet,token};}
async function event(walletId:string,tokenId:string,type:string,time:string,tokenAmount:number|null,quoteAmount:number|null,extra:any={}){return ctx.prisma.walletEvent.create({data:{dedupeKey:`${walletId}-${type}-${time}-${Math.random()}`,walletId,tokenId,signature:syntheticAddress(8000+Math.floor(Math.random()*1000)),eventType:type,tokenAmount,quoteAmount,quoteMint:'SOL',blockTime:new Date(time),confidence:'CONFIRMED',decoderVersion:2,networkFeeSol:.001,platformFeeSol:.002,tipSol:0,...extra}});}

describe('Phase 2A FIFO reconstruction',()=>{
 it('matches one buy/sell exactly with raw and all-in arithmetic',async()=>{const{wallet,token}=await setup();await event(wallet.id,token.id,'BUY','2026-01-01T00:00:00Z',10,1);await event(wallet.id,token.id,'SELL','2026-01-01T01:00:00Z',10,1.5);const r=await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id]}});expect(r.statusCode).toBe(200);const m=await ctx.prisma.walletTradeMatch.findFirstOrThrow();expect(m.matchedTokenAmount).toBe('10');expect(m.allocatedBuyCostSol).toBe('1');expect(m.rawRealizedPnlSol).toBe('0.5');expect(m.knownAllInRealizedPnlSol).toBe('0.494');expect(m.rawRealizedRoiPct).toBe('50');expect(m.holdingDurationSeconds).toBe(3600);});
 it('uses FIFO for a partial sell across multiple buys',async()=>{const{wallet,token}=await setup();const b1=await event(wallet.id,token.id,'BUY','2026-01-01T00:00:00Z',10,1);const b2=await event(wallet.id,token.id,'BUY','2026-01-01T00:10:00Z',10,2);await event(wallet.id,token.id,'SELL','2026-01-01T01:00:00Z',15,3);await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id]}});const ms=await ctx.prisma.walletTradeMatch.findMany({orderBy:{sequence:'asc'}});expect(ms.map(m=>[m.buyEventId,m.matchedTokenAmount])).toEqual([[b1.id,'10'],[b2.id,'5']]);const p=await ctx.prisma.walletPosition.findFirstOrThrow();expect(p.openTokenAmount).toBe('5');expect(p.status).toBe('PARTIAL');});
 it('creates separate cycles and matches several sells against one buy',async()=>{const{wallet,token}=await setup();await event(wallet.id,token.id,'BUY','2026-01-01T00:00:00Z',10,1);await event(wallet.id,token.id,'SELL','2026-01-01T00:10:00Z',4,.5);await event(wallet.id,token.id,'SELL','2026-01-01T00:20:00Z',6,.8);const secondBuy=await event(wallet.id,token.id,'BUY','2026-01-01T01:00:00Z',2,.2);await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id]}});const ps=await ctx.prisma.walletPosition.findMany({orderBy:{cycleNumber:'asc'}});expect(ps).toHaveLength(2);expect(ps[0].status).toBe('CLOSED');expect(ps[1].status).toBe('OPEN');expect(JSON.parse(ps[0].includedEventIdsJson)).not.toContain(secondBuy.id);expect(await ctx.prisma.walletTradeMatch.count()).toBe(2);});
 it('marks unmatched sells and incomplete history without inventing a loss',async()=>{const{wallet,token}=await setup(false);await event(wallet.id,token.id,'SELL','2026-01-01T01:00:00Z',4,1);await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id]}});const p=await ctx.prisma.walletPosition.findFirstOrThrow();expect(p.status).toBe('UNMATCHED_SELL');expect(p.rawRealizedPnlSol).toBeNull();expect(p.warningCodes).toContain('INCOMPLETE_WALLET_HISTORY');});
 it('treats transfers as unknown basis, never zero-cost buys',async()=>{const{wallet,token}=await setup();await event(wallet.id,token.id,'TOKEN_TRANSFER_IN','2026-01-01T00:00:00Z',5,null,{quoteMint:null,confidence:null});await event(wallet.id,token.id,'SELL','2026-01-01T01:00:00Z',2,1);await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id]}});const p=await ctx.prisma.walletPosition.findFirstOrThrow();expect(p.status).toBe('UNKNOWN_BASIS');expect(p.unknownBasisAmount).toBe('3');expect(p.rawRealizedPnlSol).toBeNull();});
 it('excludes legacy, unknown, missing amounts, and unsupported quotes with reasons',async()=>{const{wallet,token}=await setup();await event(wallet.id,token.id,'BUY','2026-01-01T00:00:00Z',1,1,{decoderVersion:1});await event(wallet.id,token.id,'BUY','2026-01-01T00:01:00Z',null,1);await event(wallet.id,token.id,'BUY','2026-01-01T00:02:00Z',1,1,{quoteMint:syntheticAddress(9999)});await event(wallet.id,token.id,'BUY','2026-01-01T00:03:00Z',1,1,{confidence:'UNKNOWN'});await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id]}});const p=await ctx.prisma.walletPosition.findFirstOrThrow();expect(p.excludedEventCount).toBe(4);expect(p.warningCodes).toContain('LEGACY_DECODER_EVENT');expect(p.warningCodes).toContain('UNSUPPORTED_QUOTE_ASSET');});
 it('validates selection, duplicates, development wallets, and supports read APIs',async()=>{const{wallet}=await setup();expect((await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[]}})).statusCode).toBe(400);expect((await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id,wallet.id]}})).json().error).toBe('duplicate_selection');const dev=await ctx.prisma.trackedWallet.create({data:{address:syntheticAddress(9001),source:'dev-seed'}});expect((await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[dev.id]}})).json().error).toBe('dev_wallet_excluded');const ok=await ctx.app.inject({method:'POST',url:'/api/wallet-positions/reconstruct',payload:{walletIds:[wallet.id]}});expect((await ctx.app.inject({method:'GET',url:'/api/wallet-position-runs/'+ok.json().runId})).statusCode).toBe(200);expect((await ctx.app.inject({method:'GET',url:'/api/wallet-profiles/'+wallet.id})).statusCode).toBe(200);});
});
