/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma relation results are normalized at the API boundary. */
import type { FastifyInstance } from 'fastify';
import type { PrismaClient } from '@prisma/client';
import { z } from 'zod';
import { analyzeWallets,MAX_QUALITY_WALLETS,releaseQualityLock,tryAcquireQualityLock } from '../services/walletQuality/analyzeWallets.js';
import { latestQualityMetricSetByWallet } from '../services/walletQuality/latestRuns.js';
const body=z.object({walletIds:z.array(z.string().min(1)).min(1).max(MAX_QUALITY_WALLETS)});const query=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),confidence:z.string().optional(),categoryType:z.string().optional()});
const parse=(s:string)=>{try{return JSON.parse(s) as unknown}catch{return{}}};
const dto=(m:any)=>({...m,warningCodes:parse(m.warningCodes),consistency:parse(m.consistencyJson),holdingBuckets:parse(m.holdingBucketsJson),outcomeMetrics:parse(m.outcomeMetricsJson),consistencyJson:undefined,holdingBucketsJson:undefined,outcomeMetricsJson:undefined,calculatedAt:m.calculatedAt.toISOString(),createdAt:m.createdAt.toISOString(),updatedAt:m.updatedAt.toISOString(),categories:m.categories?.map((c:any)=>({...c,warningCodes:parse(c.warningCodes)})),timeWindows:m.timeWindows?.map((w:any)=>({...w,warningCodes:parse(w.warningCodes),windowStart:w.windowStart?.toISOString()??null,windowEnd:w.windowEnd?.toISOString()??null}))});
export function registerWalletQualityRoutes(app:FastifyInstance,prisma:PrismaClient){
 app.post('/api/wallet-quality/analyze',async(req,reply)=>{const p=body.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'validation_error'});if(new Set(p.data.walletIds).size!==p.data.walletIds.length)return reply.code(400).send({error:'duplicate_selection'});const wallets=await prisma.trackedWallet.findMany({where:{id:{in:p.data.walletIds}}});if(wallets.length!==p.data.walletIds.length)return reply.code(400).send({error:'unknown_wallet'});if(wallets.some(w=>w.source==='dev-seed'))return reply.code(400).send({error:'dev_wallet_excluded'});if(!tryAcquireQualityLock())return reply.code(409).send({error:'analysis_in_progress'});try{return await analyzeWallets(prisma,wallets)}finally{releaseQualityLock();}});
 app.get('/api/wallet-quality',async(req,reply)=>{const q=query.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'validation_error'});const ids=[...(await latestQualityMetricSetByWallet(prisma)).values()];const where={id:{in:ids},...(q.data.confidence?{confidence:q.data.confidence}:{})};const [items,total]=await Promise.all([prisma.walletQualityMetricSet.findMany({where,include:{trackedWallet:{select:{address:true,label:true,emoji:true}},categories:{orderBy:[{categoryType:'asc'},{categoryValue:'asc'}]},timeWindows:{orderBy:{windowType:'asc'}}},orderBy:{trackedWalletId:'asc'},skip:(q.data.page-1)*q.data.pageSize,take:q.data.pageSize}),prisma.walletQualityMetricSet.count({where})]);return{items:items.map(dto),page:q.data.page,pageSize:q.data.pageSize,total};});
 app.get('/api/wallet-quality/:walletId/categories',async(req,reply)=>{const {walletId}=req.params as any;const q=query.parse(req.query);const id=(await latestQualityMetricSetByWallet(prisma)).get(walletId);if(!id)return reply.code(404).send({error:'quality_metrics_not_found'});const items=await prisma.walletCategoryMetric.findMany({where:{metricSetId:id,...(q.categoryType?{categoryType:q.categoryType}:{})},orderBy:[{categoryType:'asc'},{categoryValue:'asc'}]});return{items:items.map(x=>({...x,warningCodes:parse(x.warningCodes)}))};});
 app.get('/api/wallet-quality/:walletId/time-windows',async(req,reply)=>{const {walletId}=req.params as any;const id=(await latestQualityMetricSetByWallet(prisma)).get(walletId);if(!id)return reply.code(404).send({error:'quality_metrics_not_found'});const items=await prisma.walletTimeWindowMetric.findMany({where:{metricSetId:id},orderBy:{windowType:'asc'}});return{items:items.map(x=>({...x,warningCodes:parse(x.warningCodes),windowStart:x.windowStart?.toISOString()??null,windowEnd:x.windowEnd?.toISOString()??null}))};});
 app.get('/api/wallet-quality/:walletId',async(req,reply)=>{const {walletId}=req.params as any;const id=(await latestQualityMetricSetByWallet(prisma)).get(walletId);if(!id)return reply.code(404).send({error:'quality_metrics_not_found'});const m=await prisma.walletQualityMetricSet.findUnique({where:{id},include:{trackedWallet:{select:{address:true,label:true,emoji:true}},analysisRun:true,categories:{orderBy:[{categoryType:'asc'},{categoryValue:'asc'}]},timeWindows:{orderBy:{windowType:'asc'}}}});return dto(m);});
 app.get('/api/wallet-quality-runs/:id',async(req,reply)=>{const {id}=req.params as any;const r=await prisma.walletQualityAnalysisRun.findUnique({where:{id}});if(!r)return reply.code(404).send({error:'quality_run_not_found'});return{...r,startedAt:r.startedAt.toISOString(),completedAt:r.completedAt?.toISOString()??null,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()};});
}
