/**
 * Synthetic strategy-lab fixtures.
 *
 * Every address is generated by `syntheticAddress` — no real wallet address,
 * label or transaction ever appears in an automated test.
 */
import type { WalletEvent, WalletPosition } from '@prisma/client';
import type { PrismaClient } from '@prisma/client';
import { syntheticAddress } from '@memecoin-lab/shared';
import type { CycleInput } from '../../src/services/walletStrategies/fingerprint.js';

export const BASE_TIME = new Date('2026-05-01T00:00:00Z').getTime();
export const at = (offsetSeconds: number) => new Date(BASE_TIME + offsetSeconds * 1000);

let counter = 0;
export const nextId = (prefix: string) => `${prefix}-${(counter += 1)}`;
export const resetIds = () => {
  counter = 0;
};

export interface LegSpec {
  /** Seconds after BASE_TIME. */
  at: number;
  /** Exact SOL quote of the swap leg. */
  sol: number | string;
  tokens: number;
  /** Known attributable fees; null models an event whose fees are unknown. */
  fees?: number | null;
  venue?: string;
  router?: string;
  confidence?: 'CONFIRMED' | 'LIKELY';
}

export function makeEvent(type: 'BUY' | 'SELL', spec: LegSpec, walletId = 'wallet-1'): WalletEvent {
  const fees = spec.fees === undefined ? 0.001 : spec.fees;
  return {
    id: nextId(type.toLowerCase()),
    dedupeKey: nextId('dedupe'),
    walletId,
    tokenId: 'token-1',
    signature: nextId('sig'),
    eventType: type,
    tokenAmount: spec.tokens,
    quoteMint: 'SOL',
    quoteAmount: Number(spec.sol),
    source: spec.router ?? 'AXIOM',
    slot: 1,
    blockTime: at(spec.at),
    createdAt: at(spec.at),
    venue: spec.venue ?? 'PUMP_AMM',
    confidence: spec.confidence ?? 'CONFIRMED',
    explanation: null,
    swapInMint: null,
    swapInAmount: null,
    swapOutMint: null,
    swapOutAmount: null,
    walletSolChange: null,
    networkFeeSol: fees,
    priorityFeeSol: null,
    platformFeeSol: fees === null ? null : 0,
    tipSol: fees === null ? null : 0,
    rentSol: 0.002,
    unrelatedSolIn: null,
    unrelatedSolOut: null,
    unattributedSol: null,
    decoderVersion: 2,
  } as WalletEvent;
}

export interface CycleSpec {
  tokenId?: string;
  buys: LegSpec[];
  sells?: LegSpec[];
  status?: string;
  openTokens?: number;
  transferIn?: number;
  transferOut?: number;
  unmatchedSell?: number;
  unknownBasis?: number;
  rawResultSol?: string | null;
}

/** Build one in-memory cycle (position + its included events) for the pure calculator. */
export function makeCycle(spec: CycleSpec, cycleNumber = 1): CycleInput {
  const events = [
    ...spec.buys.map((buy) => makeEvent('BUY', buy)),
    ...(spec.sells ?? []).map((sell) => makeEvent('SELL', sell)),
  ].map((event) => ({ ...event, tokenId: spec.tokenId ?? 'token-1' }));
  const times = events.flatMap((e) => (e.blockTime ? [e.blockTime.getTime()] : []));
  const openedAt = new Date(Math.min(...times));
  const sells = spec.sells ?? [];
  const openTokens = spec.openTokens ?? 0;
  const status = spec.status ?? (sells.length && !openTokens ? 'CLOSED' : openTokens ? 'PARTIAL' : 'OPEN');
  const closedAt = status === 'CLOSED' && sells.length ? at(sells[sells.length - 1].at) : null;
  const cost = spec.buys.reduce((total, buy) => total + Number(buy.sol), 0);
  const position = {
    id: nextId('position'),
    reconstructionRunId: 'reconstruction-1',
    trackedWalletId: 'wallet-1',
    tokenId: spec.tokenId ?? 'token-1',
    cycleNumber,
    status,
    confidence: 'HIGH',
    openedAt,
    closedAt,
    firstBuyEventId: events[0]?.id ?? null,
    lastEventAt: new Date(Math.max(...times)),
    quoteAsset: 'SOL',
    totalBoughtTokenAmount: String(spec.buys.reduce((total, buy) => total + buy.tokens, 0)),
    totalSoldTokenAmount: String(sells.reduce((total, sell) => total + sell.tokens, 0)),
    openTokenAmount: String(openTokens),
    knownCostBasisSol: String(cost),
    knownProceedsSol: String(sells.reduce((total, sell) => total + Number(sell.sol), 0)),
    allocatedKnownFeesSol: null,
    rawRealizedPnlSol: spec.rawResultSol === undefined ? '0.05' : spec.rawResultSol,
    knownAllInRealizedPnlSol: null,
    rawRealizedRoiPct: null,
    knownAllInRealizedRoiPct: null,
    estimatedCurrentValueSol: null,
    estimatedCurrentValueUsd: null,
    estimatedUnrealizedPnlSol: null,
    estimatedUnrealizedRoiPct: null,
    valuationSnapshotId: null,
    valuationObservedAt: null,
    valuationFreshness: null,
    valuationStatus: null,
    holdingDurationSeconds: closedAt
      ? Math.floor((closedAt.getTime() - openedAt.getTime()) / 1000)
      : null,
    transferInAmount: String(spec.transferIn ?? 0),
    transferOutAmount: String(spec.transferOut ?? 0),
    unmatchedSellAmount: String(spec.unmatchedSell ?? 0),
    unknownBasisAmount: String(spec.unknownBasis ?? 0),
    includedEventCount: events.length,
    excludedEventCount: 0,
    includedEventIdsJson: JSON.stringify(events.map((e) => e.id)),
    exclusionReasonsJson: '[]',
    decoderVersionsJson: '[2]',
    warningCodes: '[]',
    calculationVersion: 1,
    calculatedAt: openedAt,
    createdAt: openedAt,
    updatedAt: openedAt,
  } as WalletPosition;
  return { position, events };
}

/** N identical single-buy/single-sell cycles — a convenient "enough sample" baseline. */
export function simpleCycles(count: number, overrides: Partial<CycleSpec> = {}): CycleInput[] {
  return Array.from({ length: count }, (_, index) =>
    makeCycle(
      {
        tokenId: `token-${index + 1}`,
        buys: [{ at: index * 10_000, sol: 0.2, tokens: 1000 }],
        sells: [{ at: index * 10_000 + 600, sol: 0.25, tokens: 1000 }],
        ...overrides,
      },
      index + 1,
    ),
  );
}

/** Persist a wallet with a COMPLETED reconstruction so the analyze route has prerequisites. */
export async function seedWallet(
  prisma: PrismaClient,
  options: {
    seed: number;
    cycles?: CycleSpec[];
    completeHistory?: boolean;
    label?: string;
    source?: string;
    withReconstruction?: boolean;
    reconstructionRunId?: string;
    reconstructionCompletedAt?: Date;
  },
) {
  const wallet = await prisma.trackedWallet.create({
    data: {
      address: syntheticAddress(options.seed),
      label: options.label ?? null,
      source: options.source ?? 'activity',
    },
  });
  const token = await prisma.token.create({
    data: { mintAddress: syntheticAddress(options.seed + 500), source: 'activity' },
  });
  await prisma.walletSyncState.create({
    data: {
      walletId: wallet.id,
      status: 'idle',
      backfillComplete: options.completeHistory ?? false,
      totalEvents: 0,
    },
  });
  if (options.withReconstruction === false) return { wallet, token, run: null };

  const run = await prisma.walletPositionReconstructionRun.create({
    data: {
      ...(options.reconstructionRunId ? { id: options.reconstructionRunId } : {}),
      status: 'COMPLETED',
      completedAt: options.reconstructionCompletedAt ?? new Date('2026-05-02T00:00:00Z'),
    },
  });
  await prisma.walletBehaviorProfile.create({
    data: {
      reconstructionRunId: run.id,
      trackedWalletId: wallet.id,
      status: 'PARTIAL',
      confidence: 'LOW',
      completeHistory: options.completeHistory ?? false,
    },
  });

  for (const [index, spec] of (options.cycles ?? []).entries()) {
    const cycle = makeCycle(spec, index + 1);
    const created: string[] = [];
    for (const event of cycle.events) {
      const stored = await prisma.walletEvent.create({
        data: {
          dedupeKey: `${wallet.id}:${event.id}`,
          walletId: wallet.id,
          tokenId: token.id,
          signature: event.signature,
          eventType: event.eventType,
          tokenAmount: event.tokenAmount,
          quoteMint: event.quoteMint,
          quoteAmount: event.quoteAmount,
          source: event.source,
          slot: event.slot,
          blockTime: event.blockTime,
          venue: event.venue,
          confidence: event.confidence,
          networkFeeSol: event.networkFeeSol,
          platformFeeSol: event.platformFeeSol,
          tipSol: event.tipSol,
          rentSol: event.rentSol,
          decoderVersion: 2,
        },
      });
      created.push(stored.id);
    }
    const p = cycle.position;
    await prisma.walletPosition.create({
      data: {
        reconstructionRunId: run.id,
        trackedWalletId: wallet.id,
        tokenId: token.id,
        cycleNumber: index + 1,
        status: p.status,
        confidence: p.confidence,
        openedAt: p.openedAt,
        closedAt: p.closedAt,
        lastEventAt: p.lastEventAt,
        totalBoughtTokenAmount: p.totalBoughtTokenAmount,
        totalSoldTokenAmount: p.totalSoldTokenAmount,
        openTokenAmount: p.openTokenAmount,
        knownCostBasisSol: p.knownCostBasisSol,
        knownProceedsSol: p.knownProceedsSol,
        rawRealizedPnlSol: p.rawRealizedPnlSol,
        holdingDurationSeconds: p.holdingDurationSeconds,
        transferInAmount: p.transferInAmount,
        transferOutAmount: p.transferOutAmount,
        unmatchedSellAmount: p.unmatchedSellAmount,
        unknownBasisAmount: p.unknownBasisAmount,
        includedEventCount: created.length,
        includedEventIdsJson: JSON.stringify(created),
        warningCodes: '[]',
      },
    });
  }
  return { wallet, token, run };
}
