// Synthetic test data only — never real wallet addresses or signatures.
import type {
  ActivityEvent,
  FocusCohort,
  FomoSummary,
  MarketSnapshot,
  PaperCallRecord,
  PaperPositionRecord,
  SlowCookCandidate,
  SlowCookResult,
  SlowCookWalletStyleMemory,
  StrategyFingerprint,
  StrategyPattern,
  Token,
  WalletEntryOutcome,
} from '../src/api';

export const FAKE_WALLET = {
  address: 'FAKEwa11etAddressForTests11111111111111111',
  label: 'mr phoof',
  emoji: null as string | null,
};

export const FAKE_MINT = 'FAKEmintAddressForTests1111111111111111111';

export function makeEvent(overrides: Partial<ActivityEvent> = {}): ActivityEvent {
  return {
    id: 'evt-1',
    walletId: 'wallet-1',
    wallet: { ...FAKE_WALLET },
    tokenId: 'token-1',
    token: { mintAddress: FAKE_MINT, name: null, symbol: null },
    signature: 'FAKEsignatureForTests111111111111111111111111111111111111111111',
    eventType: 'BUY',
    tokenAmount: 15_606_894.907348,
    quoteMint: 'SOL',
    quoteAmount: 1.510707025,
    source: 'PUMP_FUN',
    venue: 'PUMP_FUN',
    confidence: 'CONFIRMED',
    explanation: 'Reconstructed from venue instruction transfers on PUMP_FUN.',
    swapInMint: 'SOL',
    swapInAmount: 1.510707025,
    swapOutMint: FAKE_MINT,
    swapOutAmount: 15_606_894.907348,
    walletSolChange: -1.539427863,
    networkFeeSol: 0.000307,
    priorityFeeSol: 0.000302,
    platformFeeSol: 0.026339758,
    tipSol: 0,
    rentSol: 0.00207408,
    unrelatedSolIn: 0,
    unrelatedSolOut: 0,
    unattributedSol: 0,
    decoderVersion: 2,
    blockTime: '2026-07-10T21:43:50.000Z',
    ...overrides,
  };
}

export function makeMarketSnapshot(overrides: Partial<MarketSnapshot> = {}): MarketSnapshot {
  return {
    id: 'snap-1',
    tokenId: 'token-1',
    refreshRunId: 'run-1',
    observedAt: '2026-07-12T00:00:00.000Z',
    fetchedAt: '2026-07-12T00:00:00.000Z',
    ageSeconds: 42,
    freshness: 'FRESH',
    priceUsd: '0.000004089',
    priceSol: '0.00000005243',
    marketCapUsd: '363418575',
    fdvUsd: '400000000',
    liquidityUsd: '122349.87',
    volume5mUsd: '210.6',
    volume1hUsd: '6390.7',
    volume6hUsd: '26875.2',
    volume24hUsd: '260503.7',
    buys5m: 3,
    sells5m: 16,
    buys1h: 133,
    sells1h: 86,
    buys6h: 819,
    sells6h: 656,
    buys24h: 3322,
    sells24h: 5608,
    priceChange5mPct: '0.11',
    priceChange1hPct: '-0.37',
    priceChange6hPct: '-0.88',
    priceChange24hPct: '-0.6',
    pairAddress: 'FAKEpairAddress1111111111111111111111111111',
    dex: 'raydium',
    baseMint: 'FAKEmintAddressForTests1111111111111111111',
    quoteMint: 'So11111111111111111111111111111111111111112',
    tokenName: 'Fixture Meme',
    tokenSymbol: 'FIXT',
    source: 'dexscreener',
    status: 'COMPLETE',
    confidence: 'HIGH',
    selectionReason: 'only_usable_pair',
    sanitizedErrorCode: null,
    ...overrides,
  };
}

export function makeToken(overrides: Partial<Token> = {}): Token {
  return {
    id: 'token-1',
    mintAddress: 'FAKErealMint11111111111111111111111111111',
    name: 'Fixture Meme',
    symbol: 'FIXT',
    stage: 'UNCLASSIFIED',
    source: 'activity',
    discoveredAt: '2026-07-10T00:00:00.000Z',
    lastSeenAt: '2026-07-11T00:00:00.000Z',
    market: null,
    ...overrides,
  };
}

// --- Phase 2C-A: focus cohorts and strategy fingerprints ---

export function makePattern(overrides: Partial<StrategyPattern> = {}): StrategyPattern {
  return {
    id: 'pattern-1',
    fingerprintId: 'fingerprint-1',
    patternType: 'ENTRY_COUNT',
    patternValue: '1 buy',
    sortOrder: 0,
    totalCount: 5,
    eligibleCount: 2,
    excludedCount: 0,
    percentage: '40',
    medianSizeSol: '0.18',
    medianDurationSeconds: '600',
    medianRawResultSol: null,
    confidence: 'LOW',
    warningCodes: [],
    ...overrides,
  };
}

export function makeFingerprint(overrides: Partial<StrategyFingerprint> = {}): StrategyFingerprint {
  return {
    id: 'fingerprint-1',
    runId: 'strategy-run-1',
    trackedWalletId: 'wallet-1',
    reconstructionRunId: 'reconstruction-run-1',
    qualityMetricSetId: 'quality-set-1',
    calculationVersion: 1,
    status: 'COMPLETE',
    confidence: 'MEDIUM',
    eligibleCycleCount: 5,
    excludedCycleCount: 1,
    eligibleBuyCount: 8,
    eligibleSellCount: 9,
    medianBuysPerCycle: '2',
    meanBuysPerCycle: '1.6',
    p25BuysPerCycle: '1',
    p75BuysPerCycle: '2',
    singleBuyCycleCount: 2,
    twoBuyCycleCount: 2,
    multiBuyCycleCount: 1,
    medianFirstToSecondBuySeconds: '74',
    medianLaterBuyGapSeconds: '200',
    medianFirstBuySol: '0.110000123456789',
    medianCycleCostSol: '0.180000123456789',
    p75CycleCostSol: '0.44',
    medianFirstBuySharePct: '61.111111111111',
    medianLargestBuySharePct: '61.111111111111',
    largestBuyFirstCycleCount: 3,
    increasingSizeCycleCount: 1,
    cyclesWithSellCount: 5,
    medianSellsPerCycle: '2',
    singleSellCycleCount: 1,
    twoSellCycleCount: 3,
    multiSellCycleCount: 1,
    medianFirstBuyToFirstSellSeconds: '900',
    medianLastBuyToFirstSellSeconds: '600',
    medianFirstSellInventoryPct: '58.000000123456',
    medianLargestSellInventoryPct: '58.000000123456',
    medianRemainingAfterFirstSellPct: '41.999999876544',
    medianFirstSellToFinalSellSeconds: '300',
    partialFirstExitCycleCount: 4,
    fullyClosedCycleCount: 3,
    openCycleCount: 2,
    transferAffectedCycleCount: 1,
    unmatchedSellCount: 0,
    unknownBasisCycleCount: 0,
    missingFeeCycleCount: 0,
    eligibleCoveragePct: '83.333333333333',
    feeCoveragePct: '100',
    completeHistory: false,
    distinctTokenCount: 4,
    repeatedTokenCount: 1,
    repeatedTokenCycleCount: 2,
    maxCyclesPerToken: 2,
    medianSecondsBetweenTokenCycles: '7200',
    medianFeePerBuySol: '0.001',
    medianFeePerSellSol: '0.001',
    medianFeePerCycleSol: '0.004000123456789',
    medianFeeBurdenPct: '2.222222222222',
    p75FeeBurdenPct: '3.5',
    feeBurdenOver1PctCount: 4,
    feeBurdenOver2PctCount: 3,
    feeBurdenOver5PctCount: 0,
    feeBurdenOver10PctCount: 0,
    medianLegsPerCycle: '4',
    observedMaxConcurrentPositions: 3,
    medianConcurrentPositions: '2',
    descriptorCodes: ['FREQUENTLY_SCALES_IN', 'INCOMPLETE_HISTORY_SAMPLE'],
    descriptorEvidence: [
      {
        code: 'FREQUENTLY_SCALES_IN',
        formula: 'cycles with two or more buys (observed scale-in behavior) ÷ eligible cycles × 100',
        numerator: 3,
        denominator: 5,
        observed: '60',
        threshold: '40',
        sampleCount: 5,
        confidence: 'MEDIUM',
        warningCodes: ['INCOMPLETE_WALLET_HISTORY'],
      },
      {
        code: 'INCOMPLETE_HISTORY_SAMPLE',
        formula: 'the wallet backfill is not complete, so observed cycles may be missing earlier entries or later exits',
        numerator: null,
        denominator: null,
        observed: null,
        threshold: '0',
        sampleCount: 5,
        confidence: 'MEDIUM',
        warningCodes: ['INCOMPLETE_WALLET_HISTORY'],
      },
    ],
    warningCodes: ['INCOMPLETE_WALLET_HISTORY', 'SMALL_CYCLE_SAMPLE'],
    calculatedAt: '2026-07-12T00:00:00.000Z',
    patterns: [
      makePattern(),
      makePattern({ id: 'pattern-2', patternValue: '2 buys', sortOrder: 1, eligibleCount: 2, percentage: '40' }),
      makePattern({ id: 'pattern-3', patternType: 'VENUE', patternValue: 'PUMP_AMM', eligibleCount: 5, percentage: '100' }),
      makePattern({ id: 'pattern-4', patternType: 'ROUTER', patternValue: 'AXIOM', eligibleCount: 5, percentage: '100' }),
      makePattern({ id: 'pattern-5', patternType: 'HOLDING_DURATION', patternValue: '5–15 minutes', eligibleCount: 3, percentage: '60' }),
      makePattern({ id: 'pattern-6', patternType: 'FEE_BURDEN', patternValue: '2–5%', eligibleCount: 3, percentage: '60' }),
    ],
    trackedWallet: { address: FAKE_WALLET.address, label: 'bn trezor', emoji: null },
    ...overrides,
  };
}

export function makeCohort(overrides: Partial<FocusCohort> = {}): FocusCohort {
  const primaryWallet = {
    id: 'wallet-1',
    address: FAKE_WALLET.address,
    label: 'bn trezor',
    emoji: null,
    source: 'activity',
  };
  const comparisonWallet = {
    id: 'wallet-2',
    address: 'FAKEwa11etAddressForTests22222222222222222',
    label: 'bn new',
    emoji: null,
    source: 'activity',
  };
  return {
    id: 'cohort-1',
    name: 'Focus cohort A',
    description: 'User-selected wallets, possibly related.',
    createdAt: '2026-07-12T00:00:00.000Z',
    updatedAt: '2026-07-12T00:00:00.000Z',
    memberCount: 2,
    members: [
      {
        id: 'member-1',
        cohortId: 'cohort-1',
        trackedWalletId: 'wallet-1',
        role: 'PRIMARY',
        displayOrder: 0,
        notes: null,
        wallet: primaryWallet,
        createdAt: '2026-07-12T00:00:00.000Z',
        updatedAt: '2026-07-12T00:00:00.000Z',
      },
      {
        id: 'member-2',
        cohortId: 'cohort-1',
        trackedWalletId: 'wallet-2',
        role: 'COMPARISON',
        displayOrder: 0,
        notes: null,
        wallet: comparisonWallet,
        createdAt: '2026-07-12T00:00:00.000Z',
        updatedAt: '2026-07-12T00:00:00.000Z',
      },
    ],
    warningCodes: ['OWNERSHIP_NOT_ESTABLISHED', 'POSSIBLE_SHARED_LABEL_ONLY'],
    readiness: {
      'wallet-1': {
        synchronized: true,
        backfillComplete: false,
        syncStatus: 'idle',
        storedEventCount: 42,
        reconstructionRunId: 'reconstruction-run-1',
        reconstructionStatus: 'COMPLETED',
        qualityMetricSetId: 'quality-set-1',
        qualityStatus: 'COMPLETED',
        fingerprintId: 'fingerprint-1',
        fingerprintStatus: 'COMPLETE',
        fingerprintConfidence: 'MEDIUM',
        eligibleCycleCount: 5,
        missingPrerequisites: ['PARTIAL_HISTORY'],
        canAnalyze: true,
      },
      'wallet-2': {
        synchronized: false,
        backfillComplete: false,
        syncStatus: 'never synchronized',
        storedEventCount: 0,
        reconstructionRunId: null,
        reconstructionStatus: 'NONE',
        qualityMetricSetId: null,
        qualityStatus: 'NONE',
        fingerprintId: null,
        fingerprintStatus: 'NONE',
        eligibleCycleCount: null,
        fingerprintConfidence: null,
        missingPrerequisites: ['NOT_SYNCHRONIZED', 'NO_COMPLETED_RECONSTRUCTION'],
        canAnalyze: false,
      },
    },
    ...overrides,
  };
}

// --- Slow Cook V1 ---

export function makeSlowCookStyleMemory(overrides: Partial<SlowCookWalletStyleMemory> = {}): SlowCookWalletStyleMemory {
  return {
    walletId: 'wallet-1',
    address: FAKE_WALLET.address,
    label: FAKE_WALLET.label,
    evidenceState: 'SUFFICIENT',
    summarySentences: ['Often adds to a position after the first buy.', 'Evidence is based on 6 eligible completed position cycle(s).'],
    styleTags: ['FREQUENTLY_SCALES_IN'],
    metrics: {
      eligibleCycleCount: 6,
      eligibleClosedCount: 5,
      medianHoldingSeconds: '900',
      medianBuysPerCycle: '2',
      medianSellsPerCycle: '1',
      fullyClosedCycleCount: 5,
      openCycleCount: 1,
      medianFirstSellInventoryPct: '50',
      medianRemainingAfterFirstSellPct: '50',
      medianPositionSizeSol: '0.2',
      observedMaxConcurrentPositions: 2,
      rawPositiveRatePct: '60',
      medianRawRoiPct: '20',
      largestGainContributionPct: '30',
      transferAffectedCount: 0,
      unmatchedSellCount: 0,
      completeHistory: true,
    },
    ids: {
      reconstructionRunId: 'reconstruction-run-1',
      qualityMetricSetId: 'quality-set-1',
      fingerprintId: 'fingerprint-1',
      fingerprintRunId: 'strategy-run-1',
      fingerprintCalculationVersion: 1,
    },
    ...overrides,
  };
}

export function makeSlowCookCandidate(overrides: Partial<SlowCookCandidate> = {}): SlowCookCandidate {
  return {
    tokenId: 'token-1',
    mintAddress: FAKE_MINT,
    name: 'Fixture Meme',
    symbol: 'FIXT',
    state: 'HOLDING',
    confidence: 'HIGHER',
    confidenceScore: 80,
    confidenceComponents: { walletCountScore: 10, styleEvidenceScore: 20, currentnessScore: 20, marketScore: 10, contaminationPenalty: 0 },
    walletInterest: {
      walletsWithEvidenceCount: 1,
      recentBuyCount: 1,
      openPositionWalletCount: 1,
      mostRecentActivityAt: '2026-07-11T00:00:00.000Z',
    },
    accumulation: { repeatBuyWalletCount: 0, addsAfterEntryCount: 0, recentBuyCount: 1, recentSellCount: 0, stillOpenCount: 1 },
    holdingConviction: { secondsSinceFirstBuy: 86400, secondsSinceLastBuy: 86400, detectedSellCount: 0, openPositionCount: 1 },
    dataQuality: {
      contributingWalletsCurrentCount: 1,
      contributingWalletsStaleOrMissingCount: 0,
      transferAffectedWalletCount: 0,
      unmatchedSellWalletCount: 0,
      marketSnapshotStatus: 'AVAILABLE',
      marketFreshness: 'FRESH',
    },
    distributionPressure: { detectedSellCount: 0, walletsSellingCount: 0, label: 'LOW_DETECTED_DISTRIBUTION' },
    styleMatchSummary: '1 selected wallet(s) historically tend to add to positions before exiting. Their current activity on this token includes 1 detected buy(s) and no detected sell yet.',
    wallets: [
      {
        walletId: 'wallet-1',
        address: FAKE_WALLET.address,
        label: FAKE_WALLET.label,
        buyCount: 1,
        sellCount: 0,
        hasOpenPosition: true,
        firstBuyAt: '2026-07-11T00:00:00.000Z',
        lastBuyAt: '2026-07-11T00:00:00.000Z',
        styleMatch: "Current activity (1 buy(s)) matches this wallet's typical entry pattern (~2 per cycle).",
      },
    ],
    whyThisAppeared: ['1 selected wallet(s) interacted with the token', '1 recent buy(s) were detected'],
    whatCouldInvalidate: ['New sell activity could occur at any time'],
    market: {
      priceUsd: '0.000004089',
      marketCapUsd: '363418575',
      liquidityUsd: '122349.87',
      volume24hUsd: '260503.7',
      priceChange24hPct: '-0.6',
      observedAt: '2026-07-12T00:00:00.000Z',
      freshness: 'FRESH',
    },
    ...overrides,
  };
}

export function makeSlowCookResult(overrides: Partial<SlowCookResult> = {}): SlowCookResult {
  return {
    calculationVersion: 'slow-cook-v1',
    analyzedAt: '2026-07-12T00:00:00.000Z',
    requestedWalletIds: ['wallet-1'],
    options: { lookbackDays: 30, minimumWallets: 1, limit: 20, includeLowerConfidence: false },
    walletsAnalyzed: 1,
    walletsWithUsableStyle: 1,
    styleMemories: [makeSlowCookStyleMemory()],
    candidates: [makeSlowCookCandidate()],
    candidatesFound: 1,
    strongerCandidateCount: 1,
    ...overrides,
  };
}

// --- FOMO Simulator V1 ---

export function makePaperCall(overrides: Partial<PaperCallRecord> = {}): PaperCallRecord {
  return {
    id: 'call-1',
    action: 'BUY',
    conviction: 'HIGH',
    slowCookState: 'HOLDING',
    slowCookConfidence: 'HIGHER',
    slowCookMethodologyVersion: 'slow-cook-v1',
    fomoMethodologyVersion: 'fomo-sim-v1',
    analyzedAt: '2026-07-12T00:00:00.000Z',
    latestEvidenceAt: '2026-07-12T00:00:00.000Z',
    tokenId: 'token-1',
    tokenMint: FAKE_MINT,
    tokenName: 'Fixture Meme',
    tokenSymbol: 'FIXT',
    cohortKey: 'wallet-1',
    walletIds: ['wallet-1'],
    walletAddresses: [FAKE_WALLET.address],
    walletLabels: [FAKE_WALLET.label],
    styleSummaries: [],
    reasons: ['1 selected wallet(s) interacted with the token'],
    invalidation: ['New sell activity could occur at any time'],
    evidence: null,
    dataQuality: null,
    settings: { lookbackDays: 30, minimumWallets: 1, limit: 20, includeLowerConfidence: false },
    entrySnapshotId: 'snap-1',
    entryObservedAt: '2026-07-12T00:00:00.000Z',
    entryPriceUsd: '0.001',
    marketCapUsd: '1000000',
    liquidityUsd: '50000',
    volume24hUsd: '20000',
    snapshotFreshness: 'FRESH',
    simulatedAmountUsd: '100',
    feeRatePct: '0.3',
    entrySlippagePct: '1',
    exitSlippagePct: '1',
    priced: true,
    unpricedReason: null,
    warningCodes: [],
    paperPositionId: 'position-1',
    dedupeKey: 'dedupe-1',
    createdAt: '2026-07-12T00:00:00.000Z',
    ...overrides,
  };
}

export function makePaperPosition(overrides: Partial<PaperPositionRecord> = {}): PaperPositionRecord {
  return {
    id: 'position-1',
    tokenId: 'token-1',
    tokenMint: FAKE_MINT,
    tokenName: 'Fixture Meme',
    tokenSymbol: 'FIXT',
    cohortKey: 'wallet-1',
    walletIds: ['wallet-1'],
    methodologyVersion: 'fomo-sim-v1',
    status: 'OPEN',
    notionalUsd: '100',
    feeRatePct: '0.3',
    entrySlippagePct: '1',
    exitSlippagePct: '1',
    entrySnapshotId: 'snap-1',
    entryObservedAt: '2026-07-12T00:00:00.000Z',
    entryPriceUsd: '0.001',
    effectiveEntryPriceUsd: '0.00101',
    entryFeeUsd: '0.3',
    tokenQuantity: '98712.87',
    entryWarningCodes: [],
    openedAt: '2026-07-12T00:00:00.000Z',
    closedAt: null,
    exitSnapshotId: null,
    exitObservedAt: null,
    exitPriceUsd: null,
    grossExitValueUsd: null,
    exitFeeUsd: null,
    netExitValueUsd: null,
    realizedPlUsd: null,
    realizedReturnPct: null,
    latestValueUsd: '118.40',
    unrealizedPlUsd: '18.40',
    unrealizedReturnPct: '18.4',
    latestValuationAt: '2026-07-12T01:00:00.000Z',
    exitSignalPendingReason: null,
    ...overrides,
  };
}

export function makeFomoSummary(overrides: Partial<FomoSummary> = {}): FomoSummary {
  return {
    methodologyVersion: 'fomo-sim-v1',
    netPlUsd: '18.40',
    realizedPlUsd: null,
    unrealizedPlUsd: '18.40',
    openTradeCount: 1,
    closedTradeCount: 0,
    winRatePct: null,
    winningClosedCount: null,
    highConvictionPlUsd: '18.40',
    highConvictionTradeCount: 1,
    calls: { total: 1, buy: 1, hold: 0, exit: 0, avoid: 0, noTrade: 0, unpriced: 0 },
    ...overrides,
  };
}

export function makeOutcome(overrides: Partial<WalletEntryOutcome> = {}): WalletEntryOutcome {
  return {
    id: 'outcome-1',
    walletEventId: 'evt-1',
    tokenId: 'token-1',
    pairAddress: 'FAKEpairAddress1111111111111111111111111111',
    entryTime: '2026-07-10T21:43:50.000Z',
    entryPriceUsd: '0.000004000123456789',
    entryPriceMethod: 'CANDLE_OPEN',
    entryCandleTime: '2026-07-10T21:44:00.000Z',
    entryDelaySeconds: 10,
    price1mUsd: '0.0000041',
    price5mUsd: '0.0000044',
    price15mUsd: '0.0000038',
    price30mUsd: '0.0000048',
    price1hUsd: '0.000005',
    price4hUsd: '0.0000036',
    price24hUsd: '0.000006',
    return1mPct: '2.496837890625',
    return5mPct: '9.996606354413',
    return15mPct: '-5.002930801441',
    return30mPct: '19.996296410263',
    return1hPct: '24.996142095527',
    return4hPct: '-10.002776853472',
    return24hPct: '49.995370514632',
    maxPrice1hUsd: '0.0000052',
    minPrice1hUsd: '0.0000035',
    maxReturn1hPct: '29.995987841003',
    maxDrawdown1hPct: '-12.502700532777',
    timeToMax1hSeconds: 1810,
    maxPrice24hUsd: '0.0000062',
    minPrice24hUsd: '0.0000032',
    maxReturn24hPct: '54.995216260157',
    maxDrawdown24hPct: '-20.002469059009',
    timeToMax24hSeconds: 7200,
    status: 'COMPLETE',
    confidence: 'HIGH',
    coverageStart: '2026-07-10T21:44:00.000Z',
    coverageEnd: '2026-07-11T21:44:00.000Z',
    missingWindowCount: 0,
    calculationVersion: 1,
    calculatedAt: '2026-07-12T00:00:00.000Z',
    ...overrides,
  };
}
