/* eslint-disable @typescript-eslint/no-explicit-any */
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import { ModeProvider } from '../src/lib/mode';
import { WalletIntelligencePage } from '../src/pages/WalletIntelligencePage';

const wallet={id:'wallet-1',address:'FAKEwalletAddress11111111111111111111111111',label:'Research Wallet',group:null,groups:[],emoji:null,notes:null,enabled:true,source:'activity',createdAt:'2026-01-01',updatedAt:'2026-01-01'};
const profile={id:'profile-1',reconstructionRunId:'run-1',trackedWalletId:'wallet-1',calculationVersion:1,status:'PARTIAL',confidence:'LOW',eligibleBuyCount:2,eligibleSellCount:1,closedPositionCount:0,openPositionCount:0,partialPositionCount:1,unmatchedSellCount:1,transferAffectedPositionCount:1,knownPositionSizeMedianSol:'0.180000123456789',knownPositionSizeMeanSol:'0.2',knownPositionSizeP25Sol:'0.1',knownPositionSizeP75Sol:'0.3',knownPositionSizeMinSol:'0.1',knownPositionSizeMaxSol:'0.3',closedHoldingMedianSeconds:null,closedHoldingMeanSeconds:null,observedMaxConcurrentPositions:3,knownFeeBurdenMedianPct:'1.23456789123',completeHistory:false,warningCodes:['INCOMPLETE_WALLET_HISTORY','INCOMPLETE_WALLET_HISTORY'],knownBuySizesSol:['0.1','0.3'],trackedWallet:wallet};
const position={id:'pos-1',reconstructionRunId:'run-1',trackedWalletId:'wallet-1',tokenId:'token-1',cycleNumber:2,status:'UNKNOWN_BASIS',confidence:'LOW',openedAt:'2026-01-01T00:00:00Z',closedAt:null,firstBuyEventId:'buy-1',lastEventAt:'2026-01-01T01:00:00Z',quoteAsset:'SOL',totalBoughtTokenAmount:'100000000.0000000001',totalSoldTokenAmount:'20',openTokenAmount:'99999980.0000000001',knownCostBasisSol:'0.180000123456789',knownProceedsSol:'0.05',allocatedKnownFeesSol:'0.001',rawRealizedPnlSol:'0.014567890123',knownAllInRealizedPnlSol:'0.013',rawRealizedRoiPct:'41.622543208571',knownAllInRealizedRoiPct:'37',estimatedCurrentValueSol:'0.2',estimatedCurrentValueUsd:'30',estimatedUnrealizedPnlSol:null,estimatedUnrealizedRoiPct:null,valuationSnapshotId:'snap-1',valuationObservedAt:'2026-01-01',valuationFreshness:'STALE',valuationStatus:'PARTIAL',holdingDurationSeconds:null,transferInAmount:'10',transferOutAmount:'0',unmatchedSellAmount:'0',unknownBasisAmount:'10',includedEventCount:3,excludedEventCount:1,includedEventIds:['buy-1','sell-1'],exclusionReasons:['old:LEGACY_DECODER_EVENT'],decoderVersions:[1,2],warningCodes:['TRANSFER_IN_UNKNOWN_BASIS','STALE_MARKET_SNAPSHOT','STALE_MARKET_SNAPSHOT'],calculationVersion:1,calculatedAt:'2026-01-02',token:{mintAddress:'FAKEmint111111111111111111111111111111111',name:'Meme',symbol:'MEME'},matches:[{id:'match-1',buyEventId:'buy-1',sellEventId:'sell-1',sequence:0,matchedTokenAmount:'20.00000000001',allocatedBuyCostSol:'0.036123456789',allocatedBuyFeesSol:'0.0002',allocatedSellProceedsSol:'0.05',allocatedSellFeesSol:'0.0001',rawRealizedPnlSol:'0.014',knownAllInRealizedPnlSol:'0.0137',rawRealizedRoiPct:'38.888888888888',knownAllInRealizedRoiPct:'37.845',holdingDurationSeconds:3600,confidence:'HIGH',warningCodes:[],calculationVersion:1}]};
function stub(){vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{const u=String(input);let body:any;if(u.includes('/reconstruct'))body={runId:'run-1',calculationVersion:1,method:'FIFO',status:'COMPLETED',requestedWallets:1,processedWallets:1,includedEvents:3,excludedEvents:1,positionsCreated:1,matchesCreated:1,profilesCreated:1,warnings:2,failures:0,results:[]};else if(u.includes('/wallet-positions?'))body={items:[position]};else if(u.includes('/wallet-profiles'))body={items:[profile]};else body={items:[wallet],page:1,pageSize:50,total:1,stats:{total:1,enabled:1},groups:[]};return new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}});}));}
function view(mode:'simple'|'quant'='simple'){localStorage.setItem('memecoin-lab.ui-mode',mode);return render(<ModeProvider><WalletIntelligencePage/></ModeProvider>);}
describe('Wallet Intelligence',()=>{beforeEach(()=>localStorage.clear());afterEach(()=>vi.unstubAllGlobals());
it('shows disclaimer, bounded selection, and default bankroll',async()=>{stub();view();expect(screen.getByText(/does not rank wallets/)).toBeTruthy();await waitFor(()=>expect(screen.getByText('Research Wallet')).toBeTruthy());expect((screen.getByLabelText('Reference bankroll (SOL)') as HTMLInputElement).value).toBe('2.2');fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByText('1 / 10 selected')).toBeTruthy();});
it('persists valid bankroll and rejects invalid input',()=>{stub();view();const input=screen.getByLabelText('Reference bankroll (SOL)');fireEvent.change(input,{target:{value:'3.5'}});expect(localStorage.getItem('memecoin-lab.reference-bankroll-sol')).toBe('3.5');fireEvent.change(input,{target:{value:'0'}});expect(screen.getByRole('alert').textContent).toMatch(/greater than zero/);});
it('rounds Simple Mode, deduplicates readable warnings, and labels cycles',async()=>{stub();view();await waitFor(()=>screen.getByText('Research Wallet'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Reconstruct 1 selected'}));await waitFor(()=>expect(screen.getByText('1 positions')).toBeTruthy());expect(screen.getByText('8.18%')).toBeTruthy();expect(screen.getAllByText('0.18 SOL').length).toBeGreaterThan(0);expect(screen.queryByText('0.180000123456789 SOL')).toBeNull();expect(screen.getByText(/Cycle 2/)).toBeTruthy();fireEvent.click(screen.getByText('Data limitations (1)'));expect(screen.getByText(/not lifetime performance/)).toBeTruthy();fireEvent.click(screen.getByText(/MEME/));expect(screen.getByText('Data limitations (2)')).toBeTruthy();fireEvent.click(screen.getByText('Data limitations (2)'));expect(screen.getAllByText(/Token transfers affected/)).toHaveLength(1);expect(screen.getAllByText(/stale stored snapshot/)).toHaveLength(1);expect(screen.queryByText('TRANSFER_IN_UNKNOWN_BASIS')).toBeNull();expect(screen.getAllByText('100M').length).toBeGreaterThan(0);});
it('preserves exact FIFO values, warning codes, and metadata in Quant Mode',async()=>{stub();view('quant');await waitFor(()=>screen.getByText('Research Wallet'));fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Reconstruct 1 selected'}));await waitFor(()=>screen.getByText('1 positions'));fireEvent.click(screen.getByText(/MEME/));expect(screen.getByText('20.00000000001')).toBeTruthy();expect(screen.getByText('0.036123456789 SOL')).toBeTruthy();expect(screen.getByText('38.888888888888')).toBeTruthy();fireEvent.click(screen.getByText('Data limitations (2)'));expect(screen.getByText('TRANSFER_IN_UNKNOWN_BASIS')).toBeTruthy();expect(screen.getByText('FIFO')).toBeTruthy();expect(screen.getByText('run-1')).toBeTruthy();});
});
