import { useEffect, useState } from 'react';
import { api, type ReconstructionResult, type Wallet, type WalletListResponse, type WalletPosition, type WalletProfile } from '../api';
import { PageHeader } from '../components/PageHeader';
import { useMode } from '../lib/mode';
import { formatTime, shortAddr } from '../lib/format';

const BANKROLL_KEY='memecoin-lab.reference-bankroll-sol';
const unknown='Not enough reliable synchronized data.';
function n(v:string|null){const x=Number(v);return Number.isFinite(x)?x:null;}
function sol(v:string|null){return v===null?unknown:`${v} SOL`;}
function warningText(code:string){return ({INCOMPLETE_WALLET_HISTORY:'Only part of this wallet’s history has been synchronized. These figures are not lifetime performance.',UNMATCHED_SELL:'The app observed a sell without an earlier known buy in the synchronized history. Cost basis and profit cannot be determined.',OVERSELL:'Observed sells exceeded known trade inventory.',TRANSFER_IN_UNKNOWN_BASIS:'Token transfers affected this position. The full acquisition cost or remaining basis may be unknown.',TRANSFER_OUT_BASIS_REMOVED:'A transfer out reduced observed inventory without sale proceeds.',STALE_MARKET_SNAPSHOT:'The current value uses a stale stored snapshot, not a live quote.',MISSING_MARKET_SNAPSHOT:'No stored market snapshot is available for current valuation.',UNKNOWN_FEES:'Some attributable fees are unknown.'} as Record<string,string>)[code]??code;}

export function WalletIntelligencePage(){
 const {mode}=useMode(); const [wallets,setWallets]=useState<Wallet[]>([]); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<Set<string>>(new Set()); const [busy,setBusy]=useState(false); const [result,setResult]=useState<ReconstructionResult|null>(null); const [positions,setPositions]=useState<WalletPosition[]>([]); const [profiles,setProfiles]=useState<WalletProfile[]>([]); const [error,setError]=useState<string|null>(null);
 const initial=window.localStorage.getItem(BANKROLL_KEY)??'2.2'; const [bankroll,setBankroll]=useState(initial); const bankrollNumber=Number(bankroll); const validBankroll=Number.isFinite(bankrollNumber)&&bankrollNumber>0;
 useEffect(()=>{void api<WalletListResponse>('/api/wallets?pageSize=50').then(r=>setWallets(r.items.filter(w=>w.source!=='dev-seed'))).catch(e=>setError((e as Error).message));},[]);
 function changeBankroll(v:string){setBankroll(v);const x=Number(v);if(Number.isFinite(x)&&x>0)window.localStorage.setItem(BANKROLL_KEY,v);}
 function toggle(id:string){setSelected(s=>{const x=new Set(s);if(x.has(id))x.delete(id);else if(x.size<10)x.add(id);return x;});}
 async function reconstruct(){if(!selected.size||busy)return;setBusy(true);setError(null);try{const r=await api<ReconstructionResult>('/api/wallet-positions/reconstruct',{method:'POST',body:JSON.stringify({walletIds:[...selected]})});setResult(r);const [ps,pr]=await Promise.all([api<{items:WalletPosition[]}>('/api/wallet-positions?pageSize=100'),api<{items:WalletProfile[]}>('/api/wallet-profiles?pageSize=100')]);setPositions(ps.items.filter(p=>selected.has(p.trackedWalletId)));setProfiles(pr.items.filter(p=>selected.has(p.trackedWalletId)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const shown=wallets.filter(w=>(w.label??'').toLowerCase().includes(search.toLowerCase())||w.address.toLowerCase().includes(search.toLowerCase()));
 return <div><PageHeader title="Wallet Intelligence — Foundation" subtitle="Auditable FIFO position reconstruction from already synchronized activity."/>
 <p className="notice warn" role="note">This page reconstructs observed positions from synchronized history. It does not rank wallets, prove profitability, identify insiders, or recommend copying trades.</p>
 {error&&<p className="notice danger" role="alert">{error}</p>}
 <section className="panel"><h2>Select wallets</h2><p className="panel-sub">Choose up to 10 explicit wallets; start with 1–3. Reconstruction never synchronizes or re-decodes activity.</p><label className="field">Search tracked wallets<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Label or public address"/></label><div className="wallet-picker">{shown.slice(0,20).map(w=><label className="check" key={w.id}><input type="checkbox" checked={selected.has(w.id)} disabled={!selected.has(w.id)&&selected.size>=10} onChange={()=>toggle(w.id)}/>{w.emoji} {w.label??shortAddr(w.address)} <span className="mono">{shortAddr(w.address)}</span></label>)}</div><div className="toolbar"><button className="btn secondary" disabled={!selected.size} onClick={()=>setSelected(new Set())}>Clear selection</button><span>{selected.size} / 10 selected</span><button className="btn" disabled={!selected.size||busy} aria-busy={busy} onClick={()=>void reconstruct()}>{busy?'Reconstructing…':`Reconstruct ${selected.size||''} selected`}</button></div>{result&&<div className="import-summary" role="status"><span>{result.positionsCreated} positions</span><span>{result.matchesCreated} FIFO matches</span><span>{result.excludedEvents} excluded events</span><span>{result.warnings} warnings</span></div>}</section>
 <section className="panel"><h2>Reference bankroll comparison</h2><p className="panel-sub">A local comparison setting only. No wallet is connected and no balance is fetched.</p><label className="field">Reference bankroll (SOL)<input aria-label="Reference bankroll (SOL)" inputMode="decimal" value={bankroll} onChange={e=>changeBankroll(e.target.value)}/></label>{!validBankroll&&<p className="status-warn" role="alert">Enter a reference bankroll greater than zero.</p>}{profiles.map(p=><Profile key={p.id} p={p} bankroll={validBankroll?bankrollNumber:null}/>)}</section>
 <section className="panel"><h2>Reconstructed positions</h2>{!positions.length?<p className="empty-state">Select and reconstruct a wallet to inspect its observed positions.</p>:<div className="position-list">{positions.map(p=><Position key={p.id} p={p} mode={mode}/>)}</div>}</section></div>;
}
function Profile({p,bankroll}:{p:WalletProfile;bankroll:number|null}){const med=n(p.knownPositionSizeMedianSol),p75=n(p.knownPositionSizeP75Sol);const sizes=p.knownBuySizesSol.map(Number).filter(Number.isFinite);const at=(fraction:number)=>bankroll&&sizes.length?`${(sizes.filter(x=>x<=bankroll*fraction).length/sizes.length*100).toFixed(1)}%` : unknown;return <article className="card"><h3>{p.trackedWallet?.label??shortAddr(p.trackedWallet?.address??p.trackedWalletId)}</h3><div className="market-grid"><F l="Confidence" v={p.confidence}/><F l="Eligible buys / sells" v={`${p.eligibleBuyCount} / ${p.eligibleSellCount}`}/><F l="Closed / open" v={`${p.closedPositionCount} / ${p.openPositionCount}`}/><F l="Incomplete positions" v={String(p.partialPositionCount)}/><F l="Unmatched sells" v={String(p.unmatchedSellCount)}/><F l="Median known buy" v={sol(p.knownPositionSizeMedianSol)}/><F l="Mean known buy" v={sol(p.knownPositionSizeMeanSol)}/><F l="P25–P75" v={`${sol(p.knownPositionSizeP25Sol)} – ${sol(p.knownPositionSizeP75Sol)}`}/><F l="Min–max" v={`${sol(p.knownPositionSizeMinSol)} – ${sol(p.knownPositionSizeMaxSol)}`}/><F l="Median / bankroll" v={bankroll&&med!==null?`${(med/bankroll*100).toFixed(2)}%`:unknown}/><F l="P75 / bankroll" v={bankroll&&p75!==null?`${(p75/bankroll*100).toFixed(2)}%`:unknown}/><F l="Buys ≤ 5% bankroll" v={at(.05)}/><F l="Buys ≤ 10% bankroll" v={at(.1)}/><F l="Buys ≤ 20% bankroll" v={at(.2)}/><F l="Buys ≤ 25% bankroll" v={at(.25)}/><F l="Max concurrent" v={String(p.observedMaxConcurrentPositions)}/><F l="Known fee burden" v={p.knownFeeBurdenMedianPct?`${p.knownFeeBurdenMedianPct}%`:unknown}/></div>{bankroll&&med!==null&&<p>{p.observedMaxConcurrentPositions} simultaneous median-sized positions would use approximately {(med*p.observedMaxConcurrentPositions).toFixed(4)} SOL before fees.</p>}{p.warningCodes.map(w=><p className="status-warn" key={w}>{warningText(w)}</p>)}</article>}
function Position({p,mode}:{p:WalletPosition;mode:string}){const transfer=p.warningCodes.some(w=>w.startsWith('TRANSFER_'));return <details className="card"><summary><strong>{p.token?.symbol??shortAddr(p.token?.mintAddress??p.tokenId)}</strong> <span className="badge muted">{p.status}</span> — {p.confidence}</summary>{p.status==='CLOSED'&&<p>This wallet bought and later sold the known token inventory. The reconstructed raw result was {sol(p.rawRealizedPnlSol)} before all known costs.</p>}{p.status==='PARTIAL'&&<p>This wallet sold part of the known position and still has observed token inventory remaining.</p>}{p.status==='OPEN'&&<p>This observed position still has known token inventory remaining.</p>}{transfer&&<p className="status-warn">Token transfers affected this position. The full acquisition cost or remaining basis may be unknown.</p>}{p.estimatedCurrentValueSol&&<p>The current value is estimated from the latest stored market snapshot. It is not a live quote or guaranteed exit value.</p>}<div className="market-grid"><F l="Opened" v={formatTime(p.openedAt)}/><F l="Closed" v={p.closedAt?formatTime(p.closedAt):'Still open or incomplete'}/><F l="Known bought" v={p.totalBoughtTokenAmount??unknown}/><F l="Known sold" v={p.totalSoldTokenAmount??unknown}/><F l="Open amount" v={p.openTokenAmount??unknown}/><F l="Known SOL cost" v={sol(p.knownCostBasisSol)}/><F l="Known SOL proceeds" v={sol(p.knownProceedsSol)}/><F l="Raw realized result" v={sol(p.rawRealizedPnlSol)}/><F l="Known all-in result" v={sol(p.knownAllInRealizedPnlSol)}/><F l="Estimated current SOL value" v={sol(p.estimatedCurrentValueSol)}/><F l="Valuation freshness" v={p.valuationFreshness??unknown}/></div>{p.warningCodes.map(w=><p className="status-warn" key={w}>{warningText(w)}</p>)}<h4>FIFO allocations</h4>{p.matches.map(m=><div className="kv" key={m.id}><F l="Buy event" v={m.buyEventId}/><F l="Sell event" v={m.sellEventId}/><F l="Matched tokens" v={m.matchedTokenAmount}/><F l="Allocated cost" v={sol(m.allocatedBuyCostSol)}/><F l="Proceeds" v={sol(m.allocatedSellProceedsSol)}/><F l="Raw result" v={sol(m.rawRealizedPnlSol)}/>{mode==='quant'&&<><F l="Raw ROI %" v={m.rawRealizedRoiPct??'unknown'}/><F l="Known all-in ROI %" v={m.knownAllInRealizedRoiPct??'unknown'}/><F l="Calculation version" v={String(m.calculationVersion)}/><F l="Run ID" v={p.reconstructionRunId}/><F l="Method" v="FIFO"/><F l="Included event IDs" v={p.includedEventIds.join(', ')}/><F l="Decoder versions" v={p.decoderVersions.join(', ')}/><F l="Snapshot ID" v={p.valuationSnapshotId??'unknown'}/></>}</div>)}</details>}
function F({l,v}:{l:string;v:string}){return <div className="market-field"><span className="market-field-label">{l}</span><span className="market-field-value mono">{v}</span></div>}
