import { useEffect, useState } from 'react';
import { api, type QualityAnalysisResult, type QualityMetricSet, type ReconstructionResult, type Wallet, type WalletListResponse, type WalletPosition, type WalletProfile } from '../api';
import { PageHeader } from '../components/PageHeader';
import { QualityComparison, QualityPanel } from '../components/QualityEvidence';
import { useMode } from '../lib/mode';
import { formatTime, shortAddr } from '../lib/format';

const BANKROLL_KEY='memecoin-lab.reference-bankroll-sol';
const unknown='Not enough reliable synchronized data.';
function n(v:string|null){const x=Number(v);return Number.isFinite(x)?x:null;}
function rounded(v:string|null,digits=6){if(v===null)return unknown;const x=Number(v);return Number.isFinite(x)?x.toLocaleString(undefined,{maximumFractionDigits:digits}):unknown;}
function sol(v:string|null,mode:string){return v===null?unknown:`${mode==='quant'?v:rounded(v)} SOL`;}
function quantity(v:string|null,mode:string){if(v===null)return unknown;if(mode==='quant')return v;const x=Number(v);if(!Number.isFinite(x))return unknown;return new Intl.NumberFormat(undefined,{notation:Math.abs(x)>=100_000?'compact':'standard',maximumFractionDigits:4}).format(x);}
function percent(v:string|null,mode:string){return v===null?unknown:`${mode==='quant'?v:rounded(v,2)}%`;}
function warningText(code:string){return ({INCOMPLETE_WALLET_HISTORY:'Only part of this wallet’s history has been synchronized. These figures are not lifetime performance.',UNMATCHED_SELL:'The app observed a sell without an earlier known buy in the synchronized history. Cost basis and profit cannot be determined.',OVERSELL:'Observed sells exceeded known trade inventory.',TRANSFER_IN_UNKNOWN_BASIS:'Token transfers affected this position. The full acquisition cost or remaining basis may be unknown.',TRANSFER_OUT_BASIS_REMOVED:'A transfer out reduced observed inventory without sale proceeds.',STALE_MARKET_SNAPSHOT:'The current value uses a stale stored snapshot, not a live quote.',MISSING_MARKET_SNAPSHOT:'No stored market snapshot is available for current valuation.',UNKNOWN_FEES:'Some attributable fees are unknown.'} as Record<string,string>)[code]??code;}

export function WalletIntelligencePage(){
 const {mode}=useMode(); const [wallets,setWallets]=useState<Wallet[]>([]); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<Set<string>>(new Set()); const [busy,setBusy]=useState(false); const [result,setResult]=useState<ReconstructionResult|null>(null); const [positions,setPositions]=useState<WalletPosition[]>([]); const [profiles,setProfiles]=useState<WalletProfile[]>([]); const [error,setError]=useState<string|null>(null);
 const [qualityBusy,setQualityBusy]=useState(false);const [qualityResult,setQualityResult]=useState<QualityAnalysisResult|null>(null);const [quality,setQuality]=useState<QualityMetricSet[]>([]);const [compare,setCompare]=useState<string[]>([]);
 const initial=window.localStorage.getItem(BANKROLL_KEY)??'2.2'; const [bankroll,setBankroll]=useState(initial); const bankrollNumber=Number(bankroll); const validBankroll=Number.isFinite(bankrollNumber)&&bankrollNumber>0;
 useEffect(()=>{void api<WalletListResponse>('/api/wallets?pageSize=50').then(r=>setWallets(r.items.filter(w=>w.source!=='dev-seed'))).catch(e=>setError((e as Error).message));},[]);
 useEffect(()=>{void api<{items:QualityMetricSet[]}>('/api/wallet-quality?pageSize=100').then(r=>setQuality(r.items)).catch(()=>setQuality([]));},[]);
 function changeBankroll(v:string){setBankroll(v);const x=Number(v);if(Number.isFinite(x)&&x>0)window.localStorage.setItem(BANKROLL_KEY,v);}
 function toggle(id:string){setSelected(s=>{const x=new Set(s);if(x.has(id))x.delete(id);else if(x.size<10)x.add(id);return x;});}
 async function reconstruct(){if(!selected.size||busy)return;setBusy(true);setError(null);try{const r=await api<ReconstructionResult>('/api/wallet-positions/reconstruct',{method:'POST',body:JSON.stringify({walletIds:[...selected]})});setResult(r);const [ps,pr]=await Promise.all([api<{items:WalletPosition[]}>('/api/wallet-positions?pageSize=100'),api<{items:WalletProfile[]}>('/api/wallet-profiles?pageSize=100')]);setPositions(ps.items.filter(p=>selected.has(p.trackedWalletId)));setProfiles(pr.items.filter(p=>selected.has(p.trackedWalletId)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function analyze(){if(!selected.size||qualityBusy)return;setQualityBusy(true);setError(null);try{const r=await api<QualityAnalysisResult>('/api/wallet-quality/analyze',{method:'POST',body:JSON.stringify({walletIds:[...selected]})});setQualityResult(r);const q=await api<{items:QualityMetricSet[]}>('/api/wallet-quality?pageSize=100');setQuality(q.items);}catch(e){setError((e as Error).message);}finally{setQualityBusy(false);}}
 function toggleCompare(id:string){setCompare(c=>c.includes(id)?c.filter(x=>x!==id):c.length<3?[...c,id]:c);}
 const shown=wallets.filter(w=>(w.label??'').toLowerCase().includes(search.toLowerCase())||w.address.toLowerCase().includes(search.toLowerCase()));
 return <div><PageHeader title="Wallet Intelligence — Foundation" subtitle="Auditable FIFO position reconstruction from already synchronized activity."/>
 <p className="notice warn" role="note">This page reconstructs observed positions from synchronized history. It does not rank wallets, prove profitability, identify insiders, or recommend copying trades.</p>
 {error&&<p className="notice danger" role="alert">{error}</p>}
 <section className="panel"><h2>Select wallets</h2><p className="panel-sub">Choose up to 10 explicit wallets; start with 1–3. Reconstruction never synchronizes or re-decodes activity.</p><label className="field">Search tracked wallets<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Label or public address"/></label><div className="wallet-picker">{shown.slice(0,20).map(w=><label className="check" key={w.id}><input type="checkbox" checked={selected.has(w.id)} disabled={!selected.has(w.id)&&selected.size>=10} onChange={()=>toggle(w.id)}/>{w.emoji} {w.label??shortAddr(w.address)} <span className="mono">{shortAddr(w.address)}</span></label>)}</div><div className="toolbar"><button className="btn secondary" disabled={!selected.size} onClick={()=>setSelected(new Set())}>Clear selection</button><span>{selected.size} / 10 selected</span><button className="btn" disabled={!selected.size||busy} aria-busy={busy} onClick={()=>void reconstruct()}>{busy?'Reconstructing…':`Reconstruct ${selected.size||''} selected`}</button></div>{result&&<div className="import-summary" role="status"><span>{result.positionsCreated} positions</span><span>{result.matchesCreated} FIFO matches</span><span>{result.excludedEvents} excluded events</span><span>{result.warnings} warnings</span></div>}</section>
 <section className="panel"><h2>Reference bankroll comparison</h2><p className="panel-sub">A local comparison setting only. No wallet is connected and no balance is fetched.</p><label className="field">Reference bankroll (SOL)<input aria-label="Reference bankroll (SOL)" inputMode="decimal" value={bankroll} onChange={e=>changeBankroll(e.target.value)}/></label>{!validBankroll&&<p className="status-warn" role="alert">Enter a reference bankroll greater than zero.</p>}{profiles.map(p=><Profile key={p.id} p={p} bankroll={validBankroll?bankrollNumber:null} mode={mode}/>)}</section>
 <section className="panel quality-evidence" aria-labelledby="quality-evidence"><h2 id="quality-evidence">Observed quality evidence</h2><p className="notice warn">These metrics summarize the synchronized and reconstructable sample only. They do not prove lifetime profitability or recommend copying this wallet.</p><p className="panel-sub">Select wallets above, then analyze up to 10 explicitly selected wallets (start with 1–3). A completed reconstruction must already exist; analysis never reconstructs automatically.</p><button className="btn" disabled={!selected.size||qualityBusy} aria-busy={qualityBusy} onClick={()=>void analyze()}>{qualityBusy?'Analyzing…':`Analyze ${selected.size||''} selected`}</button>{qualityResult&&<div className="import-summary" role="status"><span>{qualityResult.metricSetsCreated} metric sets</span><span>{qualityResult.eligiblePositions} eligible positions</span><span>{qualityResult.excludedPositions} excluded positions</span><span>{qualityResult.categorySetsCreated} categories</span></div>}{!quality.length?<p className="empty-state">No completed quality analysis yet. Reconstruct a wallet first, then use Analyze selected.</p>:quality.map(q=><QualityPanel key={q.id} q={q} mode={mode}/>)}</section>
 <section className="panel"><h2>Research comparison</h2><p className="notice info">Side-by-side comparison is descriptive. It is not a ranking or recommendation.</p><p className="panel-sub">Choose up to three analyzed wallets. Cards stay in your selection order.</p><div className="toolbar">{quality.map(q=><label className="check" key={q.id}><input type="checkbox" checked={compare.includes(q.id)} disabled={!compare.includes(q.id)&&compare.length>=3} onChange={()=>toggleCompare(q.id)}/>{q.trackedWallet?.label??shortAddr(q.trackedWallet?.address??q.trackedWalletId)}</label>)}</div><div className="comparison-grid">{compare.map(id=>quality.find(q=>q.id===id)).filter((q):q is QualityMetricSet=>Boolean(q)).map(q=><QualityComparison key={q.id} q={q} mode={mode} bankroll={validBankroll?bankrollNumber:null}/>)}</div></section>
 <section className="panel"><h2>Reconstructed positions</h2>{!positions.length?<p className="empty-state">Select and reconstruct a wallet to inspect its observed positions.</p>:<div className="position-list">{positions.map(p=><Position key={p.id} p={p} mode={mode}/>)}</div>}</section></div>;
}
function Profile({p,bankroll,mode}:{p:WalletProfile;bankroll:number|null;mode:string}){const med=n(p.knownPositionSizeMedianSol),p75=n(p.knownPositionSizeP75Sol);const sizes=p.knownBuySizesSol.map(Number).filter(Number.isFinite);const at=(fraction:number)=>bankroll&&sizes.length?`${(sizes.filter(x=>x<=bankroll*fraction).length/sizes.length*100).toFixed(1)}%` : unknown;return <article className="card profile-card"><h3>{p.trackedWallet?.label??shortAddr(p.trackedWallet?.address??p.trackedWalletId)}</h3><div className="market-grid profile-grid"><F l="Confidence" v={p.confidence}/><F l="Eligible buys / sells" v={`${p.eligibleBuyCount} / ${p.eligibleSellCount}`}/><F l="Closed / open" v={`${p.closedPositionCount} / ${p.openPositionCount}`}/><F l="Incomplete positions" v={String(p.partialPositionCount)}/><F l="Unmatched sells" v={String(p.unmatchedSellCount)}/><F l="Median known buy" v={sol(p.knownPositionSizeMedianSol,mode)} title="The middle known SOL buy size: half were smaller and half were larger."/><F l="Mean known buy" v={sol(p.knownPositionSizeMeanSol,mode)}/><F l="P25–P75" v={`${sol(p.knownPositionSizeP25Sol,mode)} – ${sol(p.knownPositionSizeP75Sol,mode)}`} title="The middle half of known buy sizes, from the 25th to 75th percentile."/><F l="Min–max" v={`${sol(p.knownPositionSizeMinSol,mode)} – ${sol(p.knownPositionSizeMaxSol,mode)}`}/><F l="Median / bankroll" v={bankroll&&med!==null?`${(med/bankroll*100).toFixed(2)}%`:unknown}/><F l="P75 / bankroll" v={bankroll&&p75!==null?`${(p75/bankroll*100).toFixed(2)}%`:unknown}/><F l="Buys ≤ 5% bankroll" v={at(.05)}/><F l="Buys ≤ 10% bankroll" v={at(.1)}/><F l="Buys ≤ 20% bankroll" v={at(.2)}/><F l="Buys ≤ 25% bankroll" v={at(.25)}/><F l="Max concurrent" v={String(p.observedMaxConcurrentPositions)} title="The greatest number of reconstructed position cycles observed open at the same time."/><F l="Known fee burden" v={percent(p.knownFeeBurdenMedianPct,mode)} title="Median known attributable buy-side fees divided by allocated buy cost."/></div>{bankroll&&med!==null&&<p>{p.observedMaxConcurrentPositions} simultaneous median-sized positions would use approximately {(med*p.observedMaxConcurrentPositions).toFixed(4)} SOL before fees.</p>}<DataLimitations codes={p.warningCodes} mode={mode}/></article>}
function Position({p,mode}:{p:WalletPosition;mode:string}){return <details className="card position-card"><summary className="position-summary"><span><strong>{p.token?.symbol??shortAddr(p.token?.mintAddress??p.tokenId)}</strong> · Cycle {p.cycleNumber}</span><span>{formatTime(p.openedAt)} · <span className="badge muted">{p.status}</span></span></summary>{p.status==='CLOSED'&&<p>This wallet bought and later sold the known token inventory. The reconstructed raw result was {sol(p.rawRealizedPnlSol,mode)} before all known costs.</p>}{p.status==='PARTIAL'&&<p>This wallet sold part of the known position and still has observed token inventory remaining.</p>}{p.status==='OPEN'&&<p>This observed position still has known token inventory remaining.</p>}{p.estimatedCurrentValueSol&&<p>The current value is estimated from the latest stored market snapshot. It is not a live quote or guaranteed exit value.</p>}<div className="market-grid"><F l="Opened" v={formatTime(p.openedAt)}/><F l="Closed" v={p.closedAt?formatTime(p.closedAt):'Still open or incomplete'}/><F l="Known bought" v={quantity(p.totalBoughtTokenAmount,mode)}/><F l="Known sold" v={quantity(p.totalSoldTokenAmount,mode)}/><F l="Open amount" v={quantity(p.openTokenAmount,mode)}/><F l="Known SOL cost" v={sol(p.knownCostBasisSol,mode)}/><F l="Known SOL proceeds" v={sol(p.knownProceedsSol,mode)}/><F l="Raw realized result" v={sol(p.rawRealizedPnlSol,mode)}/><F l="Known all-in result" v={sol(p.knownAllInRealizedPnlSol,mode)}/><F l="Estimated current SOL value" v={sol(p.estimatedCurrentValueSol,mode)}/><F l="Valuation freshness" v={p.valuationFreshness??unknown}/></div><DataLimitations codes={p.warningCodes} mode={mode}/><h4>FIFO allocations</h4>{p.matches.map(m=><div className="kv" key={m.id}><F l="Buy event" v={m.buyEventId}/><F l="Sell event" v={m.sellEventId}/><F l="Matched tokens" v={quantity(m.matchedTokenAmount,mode)}/><F l="Allocated cost" v={sol(m.allocatedBuyCostSol,mode)}/><F l="Proceeds" v={sol(m.allocatedSellProceedsSol,mode)}/><F l="Raw result" v={sol(m.rawRealizedPnlSol,mode)}/>{mode==='quant'&&<><F l="Raw ROI %" v={m.rawRealizedRoiPct??'unknown'}/><F l="Known all-in ROI %" v={m.knownAllInRealizedRoiPct??'unknown'}/><F l="Calculation version" v={String(m.calculationVersion)}/><F l="Run ID" v={p.reconstructionRunId}/><F l="Method" v="FIFO"/><F l="Included event IDs" v={p.includedEventIds.join(', ')}/><F l="Decoder versions" v={p.decoderVersions.join(', ')}/><F l="Snapshot ID" v={p.valuationSnapshotId??'unknown'}/></>}</div>)}</details>}
function DataLimitations({codes,mode}:{codes:string[];mode:string}){const unique=[...new Set(codes)];if(!unique.length)return null;return <details className="data-limitations"><summary>Data limitations ({unique.length})</summary><ul>{unique.map(code=><li key={code}>{mode==='quant'?<><span className="mono">{code}</span> — {warningText(code)}</>:warningText(code)}</li>)}</ul></details>}
function F({l,v,title}:{l:string;v:string;title?:string}){return <div className="market-field"><span className="market-field-label" title={title}>{l}</span><span className="market-field-value mono" title={v}>{v}</span></div>}
