export const POSITION_WARNINGS = {
  INCOMPLETE_WALLET_HISTORY: 'INCOMPLETE_WALLET_HISTORY',
  LEGACY_DECODER_EVENT: 'LEGACY_DECODER_EVENT',
  UNKNOWN_QUOTE_AMOUNT: 'UNKNOWN_QUOTE_AMOUNT',
  UNSUPPORTED_QUOTE_ASSET: 'UNSUPPORTED_QUOTE_ASSET',
  MISSING_TOKEN_AMOUNT: 'MISSING_TOKEN_AMOUNT',
  MISSING_EVENT_TIME: 'MISSING_EVENT_TIME',
  LIKELY_EVENT: 'LIKELY_EVENT',
  UNKNOWN_EVENT: 'UNKNOWN_EVENT',
  TRANSFER_IN_UNKNOWN_BASIS: 'TRANSFER_IN_UNKNOWN_BASIS',
  TRANSFER_OUT_BASIS_REMOVED: 'TRANSFER_OUT_BASIS_REMOVED',
  UNMATCHED_SELL: 'UNMATCHED_SELL',
  OVERSELL: 'OVERSELL',
  STALE_MARKET_SNAPSHOT: 'STALE_MARKET_SNAPSHOT',
  MISSING_MARKET_SNAPSHOT: 'MISSING_MARKET_SNAPSHOT',
  UNKNOWN_FEES: 'UNKNOWN_FEES',
  UNATTRIBUTED_SOL: 'UNATTRIBUTED_SOL',
} as const;

export type PositionWarning = (typeof POSITION_WARNINGS)[keyof typeof POSITION_WARNINGS];
